### ISSUE TITLE
When I add orderBy to tasks collection it doesn't orderd 

### ISSUE THREAD

**Issue by abdelkrimkr** [FirebaseExtended/make-it-so-android#11]
Fix This problem 
I want it 
How To fix When I add orderBy to tasks collection it doesn't orderd 
Or just add Order Tasks by createdAt Timestamp

**Comment by thatfiredev** [comment]
@Ronaldbennet Can you please share the full query you wrote to order the tasks?

**Comment by abdelkrimkr** [comment]
> @Ronaldbennet Can you please share the full query you wrote to order the tasks?

val query = Firebase.firestore.collection(BOOKS_COLLECTION)
            .orderBy("createdAt",  Query.Direction.ASCENDING)

        listenerRegistration = query.addSnapshotListener { value, error ->
            if (error != null) {
                onError(error)
                return@addSnapshotListener
            }
            Log.d("listenerRegistration", "addListener: $value")

            value?.documentChanges?.forEach {
                val wasDocumentDeleted = it.type == REMOVED
                val book = it.document.toObject<Book>().copy(id = it.document.id)
                onDocumentEvent(wasDocumentDeleted, book)
            }
        }

**Comment by abdelkrimkr** [comment]
@thatfiredev also when i add data to collection 
the data was randomize

I want from you to update project and add sorting data with createdAt: Timestamp

I want it help me

**Comment by abdelkrimkr** [comment]
The problem is from mutableStateMapof

**Comment by thatfiredev** [comment]
@abdelkrimkr Can you please check your logcat for errors when you use that orderBy query? You might be having an issue with indexes. You'll need to create an index in your Firebase Console to be able to order by the "createdAt" field. See more detailing about creating indexes here: https://firebase.google.com/docs/firestore/query-data/indexing

**Comment by abdelkrimkr** [comment]
@thatfiredev

Yes check it 
the problem is 
when

```
 var books = mutableStateMapOf<String, Book>()
        private set
```

also see this 
```
private fun onDocumentEvent(wasDocumentDeleted: Boolean, book: Book) {
        if (wasDocumentDeleted) books.remove(book.bookId) else books[book.bookId] = book
    }
```

this data class 
```
data class Book(
    val bookId: String = "",
    val bookName: String = "",
    val bookLink: String = "",
    val createdAt: String = Timestamp.now().seconds.toString()
    )
```
it will be Converted to List the order was gone 

`val books = viewModel.books`


```
LazyColumn(
               // ......
            ) {
                items(books.values.toList(),
                    key = { bookId ->
                        bookId.bookId
                    }
                ) { bookItem ->

                    MaterialTaskItem(
                        book = bookItem,
                        
                    ){

                     
                    }
                }
```
            
the problem from this` books.values.toList()`

**Comment by abdelkrimkr** [comment]
@thatfiredev  Thanks Bro
