### ISSUE TITLE
Multiple snackbar messages shown

### ISSUE THREAD

**Issue by mtali** [FirebaseExtended/make-it-so-android#20]
An old Snackbar message gets displayed when launching the app from the recent list 

Steps to reproduce
- Open the app, and do anything to trigger Snackbar message i.e. invalid login 
- Close the app by clicking the back button 
- Reopen the app from the recent app list
- Snackbar message will be displayed

**Comment by BobbeYo1983** [comment]
Yes, there is, what to do?

**Comment by thatfiredev** [comment]
For future reference: fixed in #44
