### ISSUE TITLE
Compile Note: Hilt_MakeItSoHiltApp.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by reknoZ** [FirebaseExtended/make-it-so-android#26]
I just downloaded the git repository while following the Codelab. Before doing anything, I compiled/ran the app and got the error message stated in the title.

**Comment by marinacoelho** [comment]
Hi @reknoZ, thanks for reporting this issue! We updated all the dependencies recently, so all the APIs are in their latest versions in the main branch. This error is not showing up in the Logcat anymore. Let me know if the error persists after you update your codebase as well.
