### ISSUE TITLE
Where is TASK_DEFAULT_ID?

### ISSUE THREAD

**Issue by kalebtekle** [FirebaseExtended/make-it-so-android#28]
In the code I see a reference to TASK_DEFAULT _ID, but there is no such file. Am I missing anything?

**Comment by thatfiredev** [comment]
It's in the `MakeItSoRoutes.kt` file:

https://github.com/FirebaseExtended/make-it-so-android/blob/ed8053c746c3b5049261eaf8bb1e6fc3ca573b7e/app/src/main/java/com/example/makeitso/MakeItSoRoutes.kt#L27

It's just a default value in case the task ID wasn't passed from the previous screen to that one.

**Comment by thatfiredev** [comment]
Closing this for now.

@kalebtekle feel free to re-open if you have any more questions.
