### ISSUE TITLE
The given sign-in provider is disabled for this Firebase project

### ISSUE THREAD

**Issue by ahmrh** [FirebaseExtended/make-it-so-android#47]
Hello, I've been following the steps outlined in this codelab (https://firebase.google.com/codelabs/build-android-app-with-firebase-compose). However, upon reaching step 3 and attempting to create an account using my email and password, I encounter an error message stating, "The given sign-in provider is disabled for this Firebase project." I've already added both the email/password and anonymous sign-in providers in the Firebase console. I believe the issue doesn't lie with the `google-services.json` file since the Anonymous sign-in provider functions correctly (an anonymous user is created every time I uninstall and run the app again). Could you assist me in resolving this problem?

**Comment by HyperTK** [comment]
Me too. Please help us.

**Comment by ahmrh** [comment]
> Hi, I was also having the same problem.
> 
> [I found this article.](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection?authuser=0)

Thank you for the reply. It appears that linking anonymous accounts using linkWithCredential is no longer feasible. Is there an alternative solution or workaround available for this?

**Comment by HyperTK** [comment]
Use the REST API [signUp ](https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signUp?authuser=0)instead, passing the user's ID token in the idToken field and the email, password fields to link.
This method worked for me.
Semangat!

**Comment by ahmrh** [comment]
Alright i'll try that out later.

(also, that's a good one haha, どうも ありがとう!)
